steps:
  - id: docker-build
    name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
      - -c
      - |
        docker image build . -f Dockerfile \
        --tag gcr.io/$PROJECT_ID/staging/datatonic-$_SERVICE_NAME-$_ENVIRONMENT:$_IMAGE_VERSION \
        --cache-from gcr.io/$PROJECT_ID/staging/datatonic-$_SERVICE_NAME-$_ENVIRONMENT
  - id: docker-push
    name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
    - -c
    - |
      docker push gcr.io/$PROJECT_ID/staging/datatonic-$_SERVICE_NAME-$_ENVIRONMENT:$_IMAGE_VERSION &&
      docker image inspect gcr.io/$PROJECT_ID/staging/datatonic-$_SERVICE_NAME-$_ENVIRONMENT:$_IMAGE_VERSION --format '{{index .RepoDigests 0}}' > image-digest.txt &&
      cat image-digest.txt
  - id: vulnsign
    name: europe-west2-docker.pkg.dev/datatonic-uk-shared-services/datatonic-uk-shared-services-custom-builders/kritis-signer
    entrypoint: /bin/bash
    args:
    - -c
    - |
      /kritis/signer \
      -v=10 \
      -alsologtostderr \
      -image=$(/bin/cat image-digest.txt) \
      -policy=policy.yaml \
      -mode=check-only
    waitFor: docker-push
  - id: push-prod
    name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
    - -c
    - |
      docker tag gcr.io/$PROJECT_ID/staging/datatonic-$_SERVICE_NAME-$_ENVIRONMENT:$_IMAGE_VERSION \
      europe-west2-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID-internal-services/datatonic-$_SERVICE_NAME-$_ENVIRONMENT:$_IMAGE_VERSION && \
      docker push europe-west2-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID-internal-services/datatonic-$_SERVICE_NAME-$_ENVIRONMENT:$_IMAGE_VERSION && \
      docker tag europe-west2-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID-internal-services/datatonic-$_SERVICE_NAME-$_ENVIRONMENT:$_IMAGE_VERSION \
      europe-west2-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID-internal-services/datatonic-$_SERVICE_NAME-$_ENVIRONMENT:latest && \
      docker push europe-west2-docker.pkg.dev/$PROJECT_ID/$PROJECT_ID-internal-services/datatonic-$_SERVICE_NAME-$_ENVIRONMENT:latest \
substitutions:
  _IMAGE_VERSION: local
  _ENVIRONMENT: dev
  _SERVICE_NAME: python-api-template
