image: python:3.9.5-slim

stages:
  - test
  - image_build
  - release

coverage:
  stage: test
  image: python:3.9.5-slim-buster
  before_script:
    - pip install --upgrade pip
    - pip install poetry
    - poetry install
    - export PYTHONPATH="$PYTHONPATH:$(pwd)"
  script:
    - poetry run pytest --cov


image-build:
  stage: image_build
  image: google/cloud-sdk
  retry: 2
  before_script:
    - echo ${GCP_CREDENTIALS} > key.json
    - gcloud auth activate-service-account --key-file=key.json
  script:
    - gcloud builds submit --project=datatonic-devops-play --config=cloudbuild/container_build.yml --timeout=3600 --substitutions=_IMAGE_VERSION=${CI_COMMIT_SHORT_SHA}
  only:
    - main

# Pre-requisite for release CI Variable: GITLAB_TOKEN
release:
  image: node:14
  stage: release
  before_script:    
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
    - npm install -g semantic-release @semantic-release/exec @semantic-release/gitlab
  script:
    - npx semantic-release
  only:
    refs:
    - main
